### ISSUE TITLE
Support for the razor components

### ISSUE THREAD

**Issue by newdeal30** [FastReports/FastReport#125]
Hi there!
One question: 
Is there a plan to support the razor components / blazor framework

Thanks and regards
Michael

**Comment by newdeal30** [comment]
I'm currently writing a razor component (currently server side) for fastreport Webreport. 
My test already works. 
Are you interested to include it to the upcoming .NET Core 3.0 fastreport release?
Or would it be better to provide a seperate nuget package?

**Comment by newdeal30** [comment]
If you are interested i would like to discuss my code, because i have to do some tricks (like parsing the generated HtmlString to extract script tags)
Eventually we could do it more clean.

Thanks and regards

**Comment by newbiE247** [comment]
> If you are interested i would like to discuss my code, because i have to do some tricks (like parsing the generated HtmlString to extract script tags)
> Eventually we could do it more clean.
> 
> Thanks and regards

Hi, how can i contact you to discuss this issue? I'm trying to implement it in Blazor and also tried to parse everything within the script tag. but it didn't worked out for me just yet. Can you please share your solution? Thanks in advance.

**Comment by 8VAid8** [comment]
Hi!
Did you try to run a report script in a server-side Blazor? What about wasm? 
We are thinking about such model:
1. Preparing reports on a backand (Webreport)
2. Rendering/interactions/etc on a front (blazor webasm)

If to talk about the server-side Blazor may be it is possible to merge preparing and rendering in one component.

We are looking forward to watching details of your implementation and your code.

**Comment by newbiE247** [comment]
hi @8VAid8 ,

unfortunately i didn't manage to implement webreport as a blazor component. instead i implement it as a razor page and just open a new tab with the webreport view or designer.

i tried to parse the html, scripts and css out of the string that webreports render() method returns and inject it via jsinterop, but to no avail. 

problem is, there are still some divs that calls some js methods for updating. i can't query for these divs, because there ids are randomized at runtime. also the js code of webreport is minified and names are randomized, so i can't read it to call the methods directly via jsinterop.

i guess we have to wait for a blazor update.

**Comment by 8VAid8** [comment]
Hi, @newbiE247! We've implemented Blazor components in the [FastReport.Net](https://www.fast-report.com/en/product/fast-report-net/).
