### ISSUE TITLE
Custom Mask TextObject

### ISSUE THREAD

**Issue by jeftegoes** [FastReports/FastReport#146]
Hi!

There are some fields I need to format, I created the following (function:
```
(...)
using System.ComponentModel;
(...)
private string FormatMask(string value, string mask)
    {
      MaskedTextProvider pro = new MaskedTextProvider(mask);
      pro.Add(value);
      return pro.ToString();
    }
```

Works perfectly in FastReport Community (Preview Mode)
![work design](https://user-images.githubusercontent.com/15343678/71175637-ccf6c180-2246-11ea-8121-1f7284f6a26b.PNG)

But when using in webreport presents the error attached:
![error webreport](https://user-images.githubusercontent.com/15343678/71175641-cec08500-2246-11ea-9ce0-9988f0a52136.PNG)

I already added System.ComponentModel including

but it did not work

my json
![json](https://user-images.githubusercontent.com/15343678/71175571-a9cc1200-2246-11ea-823d-fb18e4ed187e.PNG)

**Comment by jeftegoesdev** [comment]
Does anyone know an alternative to format fields?

**Comment by eriawan** [comment]
Any use of `MaskedTextProvider` will not work for web (ASP.NET Core) at all. Because `MaskedTextProvider` requires Winforms runtime and related Winforms components (such as those in `System.ComponentModel.TypeConverter.dll` asssembly, and it is of course not available at all for web.

Therefore this bug should be closed instead of letting this marked/tegged as `help wanted`.

cc @KirillKornienko
