### ISSUE TITLE
Linux Docker

### ISSUE THREAD

**Issue by yb12306** [FastReports/FastReport#168]
I deployed fastreport in Linux docker. When I exported the image with ImageExport, some Chinese characters could not be displayed. For example, "张三", "张" can be displayed, but "三" can not be displayed. What's the reason? How to solve it?

**Comment by yung-chu** [comment]
> I deployed fastreport in Linux docker. When I exported the image with ImageExport, some Chinese characters could not be displayed. For example, "张三", "张" can be displayed, but "三" can not be displayed. What's the reason? How to solve it?

Did you finally solve it? I had a similar problem

**Comment by fediachov** [comment]
Seems same problem here https://github.com/FastReports/FastReport/issues/187
Perhaps the problem is in additional system packages in Dockerfile:
`RUN apt-get install -y xvfb x11vnc x11-xkb-utils language-pack-zh* install chinese* x11-apps libgdiplus libx11-dev fonts-arphic-ukai fonts-arphic-uming fonts-ipafont-mincho fonts-ipafont-gothic fonts-unfonts-core
`
