### ISSUE TITLE
HTMLObject information

### ISSUE THREAD

**Issue by Delamaine** [FastReports/FastReport#228]
Hi I noticed HTMLObject component available in report designer but cannot find much info on it. 

What HTML tags does it support?

Please advise where I might obtain more information.

**Comment by VitaliyRud2001** [comment]
Hello!
Documentation on HTMLObject in plans.
HTMLObject is used for direct insertion of its contents into a HTML document. TextObject also works in web, but supports a limited number of HTML tags. HTMLObject doesn't do any HTML processing on its own, so it's useless in desktop reporting - but if you need more complicated HTML markup in a web report, you should use it.
Also if you use TextObject, it will automatically measure height and weight in order to fit text inside it. (CanGrow property), while HtmlObject doesnt't support this and you should set height and width manually.
Best regards, Vitalii.
