### ISSUE TITLE
update to 2021.1 throw  Microsoft.CodeAnalysis  error

### ISSUE THREAD

**Issue by jianliulin** [FastReports/FastReport#240]
：Method not found: 'Void
Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions..ctor(Microsoft.CodeAnalysis.OutputKind, Boolean, System.String,
System.String, System.String, System.Collections.Generic.IEnumerable`1<System.String>,
Microsoft.CodeAnalysis.OptimizationLevel, Boolean, Boolean, System.String, System.String,
System.Collections.Immutable.ImmutableArray`1<Byte>, System.Nullable`1<Boolean>, Microsoft.CodeAnalysis.Platform,
Microsoft.CodeAnalysis.ReportDiagnostic, Int32,
System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,Microsoft.CodeAnalysis.Repor
tDiagnostic>>, Boolean, Boolean, Microsoft.CodeAnalysis.XmlReferenceResolver, Microsoft.CodeAnalysis.SourceReferenceResolver,
Microsoft.CodeAnalysis.MetadataReferenceResolver, Microsoft.CodeAnalysis.AssemblyIdentityComparer,
Microsoft.CodeAnalysis.StrongNameProvider, Boolean, Microsoft.CodeAnalysis.MetadataImportOptions,
Microsoft.CodeAnalysis.CSharp.NullableContextOptions)'

**Comment by vavadevds** [comment]
Hi,

This error cam from FastReport.Compat dll because it has an old reference of Microsoft.CodeAnalysis.CSharp and Microsoft.CodeAnalysis.VisualBasic dll, I think it has version 3.2.0,

But we need the 3.8.0 version or higher for the project to work without problems,

As a solution I cloned FastReport.OpenSource and FastReport.Compat repos on my local PC,
And I update packages in FastReport.OpenSource and FastReport.Compat projects,

And then I add FastReport.Compat as reference in FastReport.OpenSource and I add FastReport.OpenSource as reference in my work project :)

**Comment by nsonline** [comment]
I had the same problem……

**Comment by KirillKornienko** [comment]
Hi, I have researched this issue and it is because Microsoft.CodeAnalysis from version 3.0 to 3.2.1 inclusive is not compatible with later versions. We will update this dependency to Microsoft.CodeAnalysis 3.3.0 shortly. The downside here is that users with a fixed dependency Microsoft.CodeAnalysis 3.2.0

**Comment by rriveros13** [comment]
> Hi, I have researched this issue and it is because Microsoft.CodeAnalysis from version 3.0 to 3.2.1 inclusive is not compatible with later versions. We will update this dependency to Microsoft.CodeAnalysis 3.3.0 shortly. The downside here is that users with a fixed dependency Microsoft.CodeAnalysis 3.2.0

Hi. I trying to do what you say but my first issue is that i cant find Microsoft.CodeAnalysis 3.3.0 so i tried with 3.3.1 but i can install that version

**Comment by KirillKornienko** [comment]
Hi, latest version FastReport.Compat 2021.1.0 refers on Microsoft.CodeAnalysis 3.3.0.

**Comment by JLOrdaz** [comment]
I upgrade Microsoft.CodeAnalysis to 3.3.9 and install last version FastReport.Compact 2021.1.3

**Comment by gautamsunil1990** [comment]
Hi All,
I am getting issue as above, could you tell me what needs to updated ?

**Comment by exedor** [comment]
I am having this same issue. My project requires CodeAnalysis.Common v4.5.0 and FastReports has a dep on 4.0.1. It's interesting I have not had anything like this happen with the many, and I mean many other packages being used in the project.
