### ISSUE TITLE
How can use in my .net core 2.1 project ?

### ISSUE THREAD

**Issue by mtugnoli** [FastReports/FastReport#27]
I tried to install FastReport.OpenSource.Web from NuGet,
after this error occour :

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'Bitmap' exists in both 'CoreCompat.System.Drawing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'	My.Web	I:\MyController\PictureController.cs	201	Active

PS: I see on NyGet 2 libraries :

- FastReport.OpenSource
- FastReport.OpenSource.Web

what are the differences?

**Comment by fediachov** [comment]
Hi,

I have just checked the work of NuGet packages with a .net Core 2.1 application. Everything works fine for me. FastReport uses CoreCompat.System.Drawing because it need working on Linux and other platforms (cross-platform compatibility).  At the moment, System.Drawing.Common from .net core 2.1 does not contain all the methods we need to drawing the text and other objects. 

FastReport.OpenSource can make reports https://fastreports.github.io/FastReport.Documentation/Report.html
FastReport.OpenSource.Web can show reports in web browser https://fastreports.github.io/FastReport.Documentation/WebReport.html

Also you can look some examples here https://github.com/FastReports/FastReport/tree/master/Demos

**Comment by mtugnoli** [comment]
I do not understand why, but the problem persists ..
I do not know if it can help, but I found this article ...
https://www.hanselman.com/blog/HowDoYouUseSystemDrawingInNETCore.aspx

**Comment by fediachov** [comment]
Thanks for an article! As soon as the `System.Drawing.Common` will fully suit for FastReport, we will switch to using it. In any case, we will think about it.

**Comment by Detrav** [comment]
I’m closing this issue because it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/FastReports/FastReport/releases).

Thank you!
