### ISSUE TITLE
[BUG]Web Online Desinger  The barcode displayed in the data list is the same,BarCode type is EAN13

### ISSUE THREAD

**Issue by ArmyMedalMei** [FastReports/FastReport#325]
Web Online Desinger  The barcode displayed in the data list is the same，As shown in the figure：

![QQ截图20210903143146](https://user-images.githubusercontent.com/19337530/131961019-ee0b1a65-28b1-480c-9d3a-56c84d9f6c18.png)
![QQ截图20210903143216](https://user-images.githubusercontent.com/19337530/131961042-995b9bd3-971e-4c41-953d-60f2300d0edd.png)

**Comment by djak741** [comment]
Hello! Thank you for bug-report. Can you send me report template on e-mail s.antonenko@fast-report.com ?

**Comment by ArmyMedalMei** [comment]
We can solve this problem by selecting barcode 128 as the barcode type, but this problem still exists. You can create a new report at your side, drag a barcode, and then set the barcode type to EAN13 to see this error

**Comment by djak741** [comment]
It seems to me that this problem appeared due to the fact that the barcode is using the wrong data format, because of the default expression. Therefore, the barcode does not change its type. Also, in the screenshot, I saw that the data is written in the text component (another), and not in the text or expression field of the barcode. Try to put the barcode type EAN-13 and, for example, in its “text” field insert 978020137962, or any other in the correct format.
