### ISSUE TITLE
not have export to Excel, i need this function

### ISSUE THREAD

**Issue by huangwei16800** [FastReports/FastReport#50]
FastReport can add export to excel?   this function is important

**Comment by Detrav** [comment]
I’m closing this issue because it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/FastReports/FastReport/releases).

Thank you!

**Comment by VaskarBanerjee** [comment]
Please add Excel Export Functionality in FastReport.OpenSource. 

This functionality is very very very important.
