### ISSUE TITLE
Build error after adding to project 

### ISSUE THREAD

**Issue by Joebu** [FastReports/FastReport#68]
I get the following error after adding it to my project 
`Error	CS0433	The type 'PrinterSettings' exists in both 'CoreCompat.System.Drawing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'System.Drawing.Common, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`
using the qualified name doesn't help 

my targeted framework is netcore 2.0
dotnet version 2.1.600-preview-009472
visual studio 2017

**Comment by Detrav** [comment]
Hi, unfortunately, we are using CoreCompat.System.Drawing instead of System.Drawing.Common for graphics processing. Currently you not able to use FastReport in project with System.Drawing.Common.
I can recommend remove the System.Drawing.Common dependency and use CoreCompat.System.Drawing until the release of System.Drawing.Common.

System.Drawing.Common still not ready. Some api are not yet ready, and some have the internal modifier instead of public. Any way, we test every new build, and as soon as there is enough functionality, we will use System.Drawing.Common.
