### ISSUE TITLE
transparent page have black lines

### ISSUE THREAD

**Issue by Suddenly-TurnRound** [FastReports/FastReport#692]
I changed the background color of the report page to transparent and added white background with borderless text on the page. After exporting to PDF, black lines appear in the PDF file. What should I do

FastReport.OpenSource.Export.PdfSimple, .NET

code:
List<string> list = new List<string>();
report.Prepare();
using (MemoryStream reportImageStream = new MemoryStream())
{
    using PDFSimpleExport pdf = new PDFSimpleExport();
    pdf.PageRange = FastReport.PageRange.All;
    report.Export(pdf, reportImageStream);
    list.Add(Convert.ToBase64String(reportImageStream.ToArray()));
}
 return list;

[文件.zip](https://github.com/FastReports/FastReport/files/14896805/default.zip)

**Comment by BogdanStegachev** [comment]
Hello!

This behaviour may be due to the fact that when using FastReport.OpenSource.Export.PdfSimple, the report is exported as a picture. 

When testing this report using FastReport.Net.Demo the file turns out correctly, I send it to you below.

Export result: [test1.pdf](https://github.com/user-attachments/files/18209178/test1.pdf)

Best regards,
Bogdan
