### ISSUE TITLE
Could not load file or assembly System.Threading.Tasks.Extensions

### ISSUE THREAD

**Issue by steelunicorn** [FastReports/FastReport#699]
Using release 2024.2.0 
Get error when trying to connect Postgresql database.
![image](https://github.com/FastReports/FastReport/assets/20414473/c443693a-e5b7-4316-ae1a-38d31033b0cf)

To reproduce:
1. Open designer
2. Data -> Add data source
3. New connection -> Postgres connection
4. You don't even need to fill fields, just click 'Test connection'
5. Error

Expected to get 'Hosts can't be null' error mesage from npgsql.dll

 - OS: Windows 10
 - Version 2024.2.0
 
 Copied System.Threading.Tasks.Extensions.dll from 2022.3.0 release and that solved the issue.

**Comment by alfredoo0329** [comment]
I had the same error when connecting to MySQL from FastReport 2025.1, but with another component "System.Diagnostics.DiagnosticSource". I solved it by following the next steps:

1. Download the latest release of FastReport that works on your machine, in my case it was the 2023.3 version
2. Once you uncompress the .zip file, search the .dll file of the package the error tells you FastReport doesn´t find a match for "System.Diagnostics.DiagnosticSource.dll" or "System.Runtime.CompilerServices.Unsafe.dll" in your case
3. Copy that file to the FastReport version folder you are trying to run and replace it with the file you copied from the previous version (2023.3 -> 2025.1)
4. Open FastReport Designer again (2025.1) and the error should appear no more

Also, you would want to check if the "PublicKeyToken" that the error throws you appears in the file "Designer.exe.config" so you can be sure it will work. Otherwise, you could look for the .dll file in NuGet. However, I didn´t have to do it so I wouldn´t be sure if that could work. Good luck.

**Comment by BogdanStegachev** [comment]
Hello!

This problem has been fixed in FastReport Community Edition 2025.1.0, you will be able to update and use this connection correctly

Best regards,
Bogdan

**Comment by alexandredsimoes** [comment]
> Hello!
> 
> This problem has been fixed in FastReport Community Edition 2025.1.0, you will be able to update and use this connection correctly
> 
> Best regards, Bogdan

![Image](https://github.com/user-attachments/assets/e822ecee-227d-41d3-b895-5a87b45ca96e)

![Image](https://github.com/user-attachments/assets/e5b146e0-44d3-43d1-b593-c6e4b5cbcbdb)

2025.1.0 has the same problem

**Comment by BogdanStegachev** [comment]
Hello!

Thank you for the information provided, I have passed it to the development department and it will be resolved in future versions of FastReport Community Edition

Best regards,
Bogdan

**Comment by alexandredsimoes** [comment]
Thanks!
By the way, the solution proposed by @alfredoo0329  works like a charm.
See you later.
