### ISSUE TITLE
Could not load file or assembly System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by almendieta** [FastReports/FastReport#714]
**Describe the bug**
There is a conflict with Unsafe DLL version, designer it's asking for 4.0.4.1, but was included 6.x. I guess the problem is FastReport.Data.MySql.dll, cause MySQL needs Unsafe to work.

**To Reproduce**
1. Try to run Designer.exe in a fresh Windows 10 install. 
2. Goto Data Menu -> Add Data Source
3. In Data Source Wizard click on New Connection, select MySQL connection, fill in DB user and password, click on Test Connection button.
4. ![01](https://github.com/user-attachments/assets/eb80f070-5ec8-465f-97c4-a19d93f00d49)

**Expected behavior**
MySQL connector is not working, I noticed that in commercial version MySQL vanished from connections list, so I presume you know this bug. The problem is MySQL and MariaDB are by far the most important DBMS in the world, so it's weird you don't pay attention to this bug and solve it. 

**Device (please complete the following information):**
 - OS: Win 10 64b
 - Version 2024.2.0

**Comment by alfredoo0329** [comment]
I had the same error when connecting to MySQL from FastReport 2025.1, but with another component "System.Diagnostics.DiagnosticSource". I solved it by following the next steps:

1. Download the latest release of FastReport that works on your machine, in my case it was the 2023.3 version
2. Once you uncompress the .zip file, search the .dll file of the package the error tells you FastReport doesn´t find a match for "System.Diagnostics.DiagnosticSource.dll" or "System.Runtime.CompilerServices.Unsafe.dll" in your case
3. Copy that file to the FastReport version folder you are trying to run and replace it with the file you copied from the previous version (2023.3 -> 2025.1)
4. Open FastReport Designer again (2025.1) and the error should appear no more

Also, you would want to check if the "PublicKeyToken" that the error throws you appears in the file "Designer.exe.config" so you can be sure it will work. Otherwise, you could look for the .dll file in NuGet. However, I didn´t have to do it so I wouldn´t be sure if that could work. Good luck.

**Comment by BogdanStegachev** [comment]
Hello!

Thank you for your request, I have reproduced the problem described above and started a task in our development department, expect changes in the next versions of FastReport Community Edition

Best regards,
Bogdan
