### ISSUE TITLE
Is there any way to use FastReport OpenSource in a Blazor project?

### ISSUE THREAD

**Issue by aminmashayekhi** [FastReports/FastReport#720]
Is there any way to use FastReport OpenSource in a Blazor project?

**Comment by WBHWebDev** [comment]
Yes, it is possible to use FastReport in a Blazor application. I had it running smoothly in my Blazor project without any issues. It worked perfectly on Windows, and I was quite satisfied with the results.

However, I ran into problems when trying to run it on Linux (specifically Ubuntu). To get it to work there, you need to use the Skia version of FastReport, which unfortunately is not open-source. This turned out to be a dealbreaker for me, as our production environment runs on Linux. Therefore, my development efforts were essentially wasted.

I’m not sure if or when this functionality will be available in the open-source version, so for now, it remains a limitation.

**Comment by nonubot123** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by BogdanStegachev** [comment]
Hello!

To solve your problem you can use our test application at the following path: https://github.com/FastReports/FastReport.Blazor.Demo.

Best regards,
Bogdan

**Comment by knox007** [comment]
In FastReport. OpenSource. Web no WebReportContainer this component in the dynamic library, the commercial version of the only, is not in the OpenSource, your demo using the commercial version of the dependency  

![Image](https://github.com/user-attachments/assets/e8cb52e1-16fd-473e-ada7-0f29680b1f8f)

@BogdanStegachev

**Comment by BogdanStegachev** [comment]
Hello!

FastReport OpenSource has only Blazor Server. Full Blazor support is in the commercial version.

Best regards,
Bogdan

**Comment by BogdanStegachev** [comment]
The correct display of the report on the front end will work correctly when using the demo packages that are used in the application provided above. You will be able to test on the demo packages.

Best regards,
Bogdan

**Comment by knox007** [comment]
Hello, I have a question I would like to ask you. Is there a page limit when using FastReport Open Source to export reports as PDFs? @BogdanStegachev
