### ISSUE TITLE
REST connector

### ISSUE THREAD

**Issue by VVKot** [FastReports/FastReport#75]
Hey guys,

Is there a way to create REST "connector"? My use case - generating a report using data which will be dynamically fetched from other API. Maybe there is the other way to achieve this goal?

UPD. By "fetching from API" I mean loading data outside of the connector and passing the data into it using stream(better) or local file(still acceptable). Do you have examples of such connectors? If no - any advice on how to implement that?

**Comment by fediachov** [comment]
Hi,

You can use an existing JSON connector for access to the REST data.

![изображение](https://user-images.githubusercontent.com/43993341/55215911-532c2d00-520c-11e9-89d4-e99280d2cc3a.png)

**Comment by VVKot** [comment]
@fediachov Thanks for the suggestion. But with that solution, I can only fetch data from one URI, and I would need to change my report if API key/REST endpoint changes. Is there a way to dynamically pass data to report? My flow would look something like this:
1) fetch *.frx template
2) fetch data from different APIs
3) pass data to the template and create a report
I don't want to put all the logic from step 2 into a connector as it may change rapidly.

**Comment by Detrav** [comment]
Hello,

The report will still be made using the connector (business objects, test, real or rest). For examples, if you create a report, then you should connect a data source to the band so that the report would process them.

Several variants from best to worse, just my opinion:
1. You have added Json Connector to Report, and just replace endpoint URL or some params before report preparing
2. You have made a report with business object ( registered objects from code, no data source). Then before preparing report you have to manually get data from REST, parse them and reregister.
3. You have made a report with business object ( registered objects from code, no data source). Then before preparing report you have to manually get data from REST, parse them and reregister.

**Comment by Detrav** [comment]
[An example of a connector is here](https://github.com/FastReports/FastReport/tree/master/Extras/Core/FastReport.Data/FastReport.Data.Json)
Write us if you need code examples

**Comment by VVKot** [comment]
@Detrav Thanks for the provided variants!

I believe you accidentally copy-pasted 2nd variant into 3rd one, is there a 3rd?

Can you also provide a small code sample on the 2nd? You mean using Report.RegisterData?

**Comment by Detrav** [comment]
😫 Oh that's a misclick, sorry, the 3rd way is using fake data source on design time and register real data as Data Source.

It takes time, I will try to find the sample code in the demo

**Comment by Detrav** [comment]
```
// step 1 prepare frx
SomeClass[] fakeList = new SomeClass[0];
Report r = new Report();
r.Dictionary.RegisterData(fakeList, "SomeTable", true);
r.Save("report.frx");
```
Now the table is available in the designer.

![image](https://user-images.githubusercontent.com/5013291/55329912-6fdc9500-5498-11e9-9efd-d0b9446f1fa7.png)

Now you can make your report.

```
// load on web and register Data
List<SomeClass> data = new List<SomeClass>();
Report report = new Report();
report.Load("report.frx");  
report.RegisterData(data, "SomeTable");
```

I have made the console demo so without webreport, I think you can get a data to the data list :)

[Full code with example](https://github.com/Detrav/fr_fake_business_register/tree/master)

**Comment by VVKot** [comment]
Okay, I think I can figure it out from here on now. Thanks again for providing different approaches.
