### ISSUE TITLE
dose community version support online design?

### ISSUE THREAD

**Issue by csabc** [FastReports/FastReport#76]
dose community version support online design? if supports,how to do?

**Comment by Detrav** [comment]
Yes, of course, the Open Source version supports working with the Online Designer. It's similar to .net core version. Since they are both based on the same engine.
However, Online Designer is not part of Open Source or Community Edition 😟 

[Demo](https://github.com/FastReports/FastReport/tree/master/Demos/OpenSource/SPAOnlineDesigner)
[FastReports Blog](https://www.fast-report.com/en/blog/196/show/)
